---
- name: Install AWS CLI v2 on RHEL/CentOS
  hosts: localhost
  become: yes
  gather_facts: yes
  vars:
    aws_cli_url_x86_64: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    aws_install_tmp: "/tmp/awscliv2_install"
  tags: [awscli, aws]
  tasks:
    - name: Ensure this playbook runs only on RHEL-family hosts
      assert:
        that: "ansible_facts['os_family'] == 'RedHat'"
        fail_msg: "This playbook is intended for RHEL/CentOS family hosts."

    - name: Ensure required system packages are installed
      package:
        name:
          - unzip
          - curl
          - python3
          - groff
          - less
        state: present

    - name: Fail if architecture is unsupported
      fail:
        msg: "Unsupported architecture {{ ansible_architecture }} for AWS CLI v2."
      when: ansible_architecture not in ['x86_64']

    - name: Set the download URL for the current architecture
      set_fact:
        aws_cli_download_url: "{{ aws_cli_url_x86_64  }}"

    - name: Create temporary install directory
      file:
        path: "{{ aws_install_tmp }}"
        state: directory
        mode: '0755'

    - name: Download AWS CLI v2 archive
      get_url:
        url: "{{ aws_cli_download_url }}"
        dest: "{{ aws_install_tmp }}/awscliv2.zip"
        mode: '0644'
        timeout: 60

    - name: Unarchive AWS CLI v2
      unarchive:
        src: "{{ aws_install_tmp }}/awscliv2.zip"
        dest: "{{ aws_install_tmp }}"
        remote_src: yes

    - name: Install AWS CLI v2 (idempotent)
      command: "{{ aws_install_tmp }}/aws/install -i /usr/local/aws-cli -b /usr/local/bin"
      args:
        creates: /usr/local/bin/aws

    - name: Ensure aws binary is executable
      file:
        path: /usr/local/bin/aws
        state: file
        mode: '0755'
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Clean up temporary files
      file:
        path: "{{ aws_install_tmp }}"
        state: absent

    - name: Show installed AWS CLI version
      command: /usr/local/bin/aws --version
      register: aws_version
      changed_when: false

    - name: Display AWS CLI version
      debug:
        var: aws_version.stdout

    - name: Set SAM CLI download URLs and temp dir
      set_fact:
        sam_url_x86_64: "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip"
        sam_install_tmp: "/tmp/sam_install"

    - name: Fail if architecture is unsupported for SAM CLI
      fail:
        msg: "Unsupported architecture {{ ansible_architecture }} for AWS SAM CLI."
      when: ansible_architecture not in ['x86_64']

    - name: Set SAM download URL for current architecture
      set_fact:
        sam_download_url: "{{ sam_url_x86_64  }}"

    - name: Create temporary SAM install directory
      file:
        path: "{{ sam_install_tmp }}"
        state: directory
        mode: '0755'

    - name: Download AWS SAM CLI archive
      get_url:
        url: "{{ sam_download_url }}"
        dest: "{{ sam_install_tmp }}/aws-sam-cli.zip"
        mode: '0644'
        timeout: 60

    - name: Unarchive AWS SAM CLI
      unarchive:
        src: "{{ sam_install_tmp }}/aws-sam-cli.zip"
        dest: "{{ sam_install_tmp }}"
        remote_src: yes

    - name: Find sam binary in extracted files
      find:
        paths: "{{ sam_install_tmp }}"
        patterns: sam
        file_type: file
        recurse: yes
      register: sam_find

    - name: Install sam binary to /usr/local/bin
      copy:
        src: "{{ item.path }}"
        dest: /usr/local/bin/sam
        mode: '0755'
        remote_src: yes
      loop: "{{ sam_find.files }}"
      when: sam_find.matched > 0

    - name: Fail if sam binary not found after extraction
      fail:
        msg: "Could not find 'sam' binary in the SAM CLI archive."
      when: sam_find.matched == 0

    - name: Clean up SAM temporary files
      file:
        path: "{{ sam_install_tmp }}"
        state: absent

    - name: Show installed AWS SAM CLI version
      command: sam --version
      register: sam_version
      changed_when: false
      failed_when: false

    - name: Display AWS SAM CLI version
      debug:
        var: sam_version.stdout
