---
- name: Install EPEL repository on RHEL 10
  hosts: localhost
  become: yes

  tasks:

    - name: Ensure epel-release package is installed
      dnf:
        name: epel-release
        state: present

    - name: Enable EPEL repository
      command: dnf config-manager --set-enabled epel
      changed_when: false
      failed_when: false

    - name: Refresh dnf cache
      dnf:
        update_cache: yes

    - name: Verify EPEL repository is available
      command: dnf repolist enabled
      register: epel_repolist
      changed_when: false

    - name: Show enabled repositories
      debug:
        msg: "{{ epel_repolist.stdout_lines }}"
