- name: Install NodeJs on RHEL using dnf
  hosts: localhost
  become: yes
  vars:
    nodejs_version: "lts"

  tasks:
    - name: Ensure package metadata is up-to-date
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Add NodeSource repository (RHEL/CentOS/Rocky)
      shell: |
        curl -fsSL https://rpm.nodesource.com/setup_{{ nodejs_version }}.x | bash -


    - name: Install Node.js (RHEL/CentOS/Rocky)
      yum:
        name: nodejs
        state: present


    - name: Verify Node version
      command: node -v
      register: node_version_output

    - name: Print installed Node version
      debug:
        msg: "Installed Node.js version: {{ node_version_output.stdout }}"
